package com.se2.base.Common

object Constant {
    const val BASE_URL = "http://10.0.2.2:3000"
//    const val BASE_URL = "https://4a95-2401-d800-9e1-a29-46f-53de-9187-9626.ngrok-free.app"

    val skillSuggestions = listOf(
        // Business Skills
        "Business Strategy", "Project Management", "Financial Analysis", "Risk Management", "Change Management",
        "Business Development", "Vendor Management", "Negotiation", "Stakeholder Management", "Contract Management",
        "Team Leadership", "Entrepreneurship", "Product Management", "Sales Strategy", "Market Research",
        "Competitive Analysis", "Operational Efficiency", "Lean Management", "Customer Relationship Management",
        "Business Intelligence", "Supply Chain Management", "Cost Reduction", "Business Forecasting", "Strategic Planning",
        "Business Process Improvement", "Budgeting", "Financial Forecasting", "Pricing Strategy", "Mergers & Acquisitions",
        "Investor Relations", "International Business", "Corporate Governance", "Business Ethics", "SWOT Analysis",
        "Customer Acquisition", "B2B Sales", "B2C Sales", "CRM Software", "Salesforce", "Lead Generation", "Account Management",
        "Revenue Generation", "Product Development", "Brand Management", "Client Retention", "Sales Presentations",
        "Market Penetration", "Product Launch", "Customer Service", "Client Relationship Management", "Supply Chain Logistics",
        "Sourcing and Procurement", "Negotiation Skills", "Team Collaboration", "Project Execution", "Financial Reporting",
        "Employee Training", "Leadership Development", "Risk Assessment", "Time Management", "Business Communication",
        "Workplace Safety", "Public Speaking", "Crisis Management", "Cultural Awareness", "Human Resource Management",
        "Staff Management", "HR Software", "Employee Engagement", "Job Analysis", "Recruitment and Selection",
        "Performance Management", "Compensation and Benefits", "Labor Law", "Compliance",

        // Marketing Skills
        "Digital Marketing", "SEO", "PPC Advertising", "Google Analytics", "Content Marketing", "Email Marketing",
        "Social Media Marketing", "Influencer Marketing", "Affiliate Marketing", "Brand Management", "Event Planning",
        "Product Marketing", "Market Research", "Competitive Analysis", "Growth Hacking", "Customer Acquisition",
        "Customer Retention", "Mobile Marketing", "Conversion Rate Optimization", "Landing Page Optimization",
        "Advertising", "Google Ads", "Facebook Ads", "Instagram Marketing", "LinkedIn Marketing", "Twitter Ads",
        "Snapchat Marketing", "Pinterest Marketing", "TikTok Marketing", "Marketing Strategy", "Public Relations",
        "Media Buying", "Campaign Management", "Media Planning", "Brand Strategy", "Advertising Copywriting",
        "Graphic Design for Marketing", "Creative Direction", "Visual Storytelling", "Copywriting", "Product Photography",
        "Video Marketing", "Data-driven Marketing", "Sales Funnels", "Customer Journey Mapping", "E-commerce Marketing",
        "Google Tag Manager", "Retargeting", "Customer Insights", "Lead Nurturing", "Market Segmentation", "B2B Marketing",
        "B2C Marketing", "CRM Software", "Sales Enablement", "Business Development", "Content Creation",
        "Brand Awareness", "Customer Feedback", "Community Engagement", "Mobile App Marketing", "Loyalty Programs",
        "Online Reputation Management", "Cross-channel Marketing",

        // IT and Software Development Skills
        "Software Engineering", "Web Development", "Frontend Development", "Backend Development", "Full Stack Development",
        "JavaScript", "React", "Node.js", "Vue.js", "Angular", "HTML", "CSS", "Sass", "Less", "PHP", "Ruby",
        "Python", "Java", "C#", "C++", "Swift", "Kotlin", "TypeScript", "Go", "Rust", "SQL", "MySQL", "PostgreSQL",
        "MongoDB", "Redis", "Elasticsearch", "Docker", "Kubernetes", "AWS", "Azure", "Google Cloud", "Terraform",
        "DevOps", "CI/CD", "Jenkins", "Git", "GitHub", "GitLab", "Bitbucket", "Agile Methodology", "Scrum", "Kanban",
        "TDD", "BDD", "JUnit", "TestNG", "Selenium", "Cucumber", "Rest APIs", "GraphQL", "Cloud Computing",
        "Machine Learning", "Artificial Intelligence", "Deep Learning", "Data Science", "Data Engineering", "Big Data",
        "Apache Spark", "Hadoop", "Data Visualization", "Tableau", "Power BI", "ETL", "Data Warehousing",
        "Business Intelligence", "Data Mining", "Python Libraries (NumPy, Pandas, Matplotlib)", "R Programming",
        "SQL Optimization", "AWS Lambda", "Microservices", "Event-Driven Architecture", "Serverless Architecture",
        "Node.js", "Express.js", "Ruby on Rails", "Django", "Flask", "Spring Boot", "Laravel", "React Native", "Flutter",
        "iOS Development", "Android Development", "Xcode", "Android Studio", "Unity", "Unreal Engine", "Game Development",
        "UI/UX Design", "Automation Testing", "API Testing", "Selenium WebDriver", "Jira", "Trello", "Asana", "Confluence",

        // Graphic Design and Creative Skills
        "Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "CorelDRAW", "Sketch", "Figma", "Canva", "InVision",
        "UI/UX Design", "Web Design", "App Design", "Mobile UI Design", "Wireframing", "Prototyping", "User Research",
        "Creative Direction", "Branding", "Logo Design", "Typography", "Color Theory", "Icon Design", "Motion Graphics",
        "3D Modeling", "Adobe After Effects", "Adobe Premiere Pro", "Video Editing", "Storyboarding", "Animation",
        "Visual Storytelling", "Video Production", "Product Photography", "Product Videography", "Illustration",
        "Print Design", "Editorial Design", "Packaging Design", "Social Media Graphics", "Banner Design", "Flyer Design",
        "Business Card Design", "Brochure Design", "Magazine Layout", "Typography", "Print Production", "Advertising Design",
        "3D Rendering", "AutoCAD", "Blender", "Maya", "Cinema 4D", "Autodesk Revit", "Vector Graphics", "Web Animation",
        "User Interface Design", "Interaction Design",

        // Hospitality and Customer Service Skills
        "Customer Service", "Guest Relations", "Front Desk Management", "Housekeeping Management", "Event Planning",
        "Hotel Management", "Restaurant Management", "Food and Beverage Service", "Catering", "Concierge Services",
        "Reservation Systems", "Event Coordination", "Public Relations", "Conflict Resolution", "Sales and Marketing",
        "Menu Planning", "Bartending", "Wine Knowledge", "Hospitality Management Software", "Restaurant POS Systems",
        "Customer Satisfaction", "Complaint Management", "Team Leadership", "Multi-tasking", "Conflict Resolution",
        "Travel Coordination", "Scheduling", "Customer Loyalty Programs", "Staff Training", "Communication Skills",
        "Scheduling and Time Management", "Hotel Check-in/Check-out", "Food Safety Standards", "Staff Scheduling",
        "Tourism Management", "Room Service Management", "Business Travel Coordination", "Tour Planning", "Event Promotion",
        "Catering Management", "Business Etiquette", "Cultural Awareness", "Hotel Operations", "Concierge Services",
        "VIP Services", "Sales and Upselling", "Facility Management", "Beverage Knowledge", "Guest Satisfaction Surveys",
        "Customer Experience Management", "Sales Training", "Problem Solving", "Customer Retention",

        // Healthcare and Medical Skills
        "Patient Care", "Medical Terminology", "Medical Billing and Coding", "Electronic Health Records (EHR)",
        "HIPAA Compliance", "Clinical Research", "Medical Imaging", "Pharmacy", "Nursing", "Surgical Assistance",
        "Medical Transcription", "Healthcare Administration", "Medical Writing", "Patient Scheduling", "Healthcare IT",
        "Medical Equipment", "Blood Pressure Measurement", "Surgical Instrumentation", "Dental Hygiene", "Emergency Medicine",
        "First Aid", "CPR", "Wound Care", "Nutrition and Dietetics", "Mental Health Counseling", "Physical Therapy",
        "Phlebotomy", "Clinical Trials", "Laboratory Testing", "Health Insurance Processing", "Medical Assistant",
        "Pediatrics", "Geriatrics", "Oncology", "Anesthesia", "Cardiology", "Ophthalmology", "Podiatry", "Emergency Response",
        "Healthcare Compliance", "Insurance Verification", "Clinical Documentation", "Medical Office Administration",
        "Clinical Assessment", "Chronic Disease Management", "Health Promotion",

        // Language and Communication Skills
        "English", "Spanish", "French", "Italian", "German", "Mandarin", "Portuguese", "Russian", "Arabic", "Japanese",
        "Sign Language", "Translation", "Interpretation", "Public Speaking", "Content Writing", "Copywriting", "Technical Writing",
        "Editing", "Proofreading", "Storytelling", "Communication Strategies", "Persuasive Communication", "Non-verbal Communication",
        "Presentation Skills", "Negotiation Skills", "Cross-cultural Communication", "Active Listening", "Writing for Social Media",
        "Journalism", "Scriptwriting", "Speechwriting", "Proposal Writing", "Business Writing", "Press Releases", "Media Relations",
        "Brand Voice", "Public Relations", "Marketing Communication", "Crisis Communication", "Customer Communication",

        // Finance and Accounting Skills
        "Accounting", "Financial Analysis", "Budgeting", "Forecasting", "Bookkeeping", "Tax Preparation", "Tax Filing",
        "Financial Reporting", "Audit", "Accounts Payable", "Accounts Receivable", "General Ledger", "QuickBooks", "Xero",
        "Financial Modeling", "Investment Analysis", "Financial Planning", "Risk Management", "Cost Accounting", "CFA",
        "CMA", "Forensic Accounting", "Corporate Finance", "Mergers & Acquisitions", "Credit Risk Analysis", "Cash Flow Management",
        "Reconciliation", "Internal Controls", "Payroll Management", "Banking",

        // Engineering Skills
        "Mechanical Engineering", "Electrical Engineering", "Civil Engineering", "Industrial Engineering", "Chemical Engineering",
        "Aerospace Engineering", "Structural Engineering", "Construction Management", "Automotive Engineering", "Robotics",
        "CAD Design", "SolidWorks", "AutoCAD", "Revit", "Project Engineering", "Manufacturing", "HVAC Systems",
        "Electrical Systems", "Thermodynamics", "Materials Science", "Process Engineering", "Welding", "Industrial Automation",
        "Control Systems", "Safety Standards", "Product Design", "Engineering Design", "Finite Element Analysis (FEA)",
        "Automation Engineering", "3D Printing", "Simulation Modeling"
    )

    val universitySuggestions = listOf(
        "University of Oxford (UK)", "University of Cambridge (UK)", "Imperial College London (UK)",
        "London School of Economics and Political Science (LSE) (UK)", "University College London (UCL) (UK)",
        "King's College London (UK)", "University of Edinburgh (UK)", "University of Manchester (UK)",
        "University of Warwick (UK)", "University of Bristol (UK)", "ETH Zurich (Switzerland)", "EPFL (Switzerland)",
        "University of Amsterdam (Netherlands)", "Leiden University (Netherlands)", "Delft University of Technology (Netherlands)",
        "University of Copenhagen (Denmark)", "Aarhus University (Denmark)", "University of Helsinki (Finland)",
        "Helsinki University of Technology (Finland)", "KTH Royal Institute of Technology (Sweden)",
        "Stockholm University (Sweden)", "Uppsala University (Sweden)", "University of Barcelona (Spain)",
        "Autonomous University of Barcelona (Spain)", "Complutense University of Madrid (Spain)", "University of Valencia (Spain)",
        "Sorbonne University (France)", "Université PSL (Paris Sciences et Lettres) (France)", "University of Paris-Saclay (France)",
        "Université Grenoble Alpes (France)", "University of Milan (Italy)", "Politecnico di Milano",
        "Vita-Salute San Raffaele University",
        "University of Bologna (Italy)", "Sapienza University of Rome (Italy)", "University of Padua (Italy)",
        "University of Vienna (Austria)", "Vienna University of Technology (Austria)", "University of Salzburg (Austria)",
        "Ludwig Maximilian University of Munich (Germany)", "University of Heidelberg (Germany)", "Technical University of Munich (Germany)",
        "Humboldt University of Berlin (Germany)", "University of Göttingen (Germany)", "RWTH Aachen University (Germany)",
        "Freie Universität Berlin (Germany)", "University of Mannheim (Germany)", "Karlsruhe Institute of Technology (Germany)",
        "Ecole Normale Supérieure (France)", "University of Warsaw (Poland)", "Jagiellonian University (Poland)",
        "University of Wrocław (Poland)", "Charles University (Czech Republic)", "Masaryk University (Czech Republic)",
        "University of Belgrade (Serbia)", "University of Zagreb (Croatia)", "University of Bucharest (Romania)",
        "Bucharest University of Economic Studies (Romania)", "University of Ljubljana (Slovenia)", "University of Sofia (Bulgaria)",
        "University of Porto (Portugal)", "University of Lisbon (Portugal)", "Universidade Nova de Lisboa (Portugal)",
        "University of Aberdeen (UK)", "University of Exeter (UK)", "University of York (UK)", "University of Sheffield (UK)",
        "University of Leeds (UK)", "University of Glasgow (UK)", "University of St Andrews (UK)", "University of Durham (UK)",
        "University of Sussex (UK)", "University of Nottingham (UK)", "University of Southampton (UK)", "University of Reading (UK)",
        "University of Kent (UK)", "University of Surrey (UK)", "Cardiff University (UK)", "University of Leicester (UK)",
        "University of Bath (UK)", "University of East Anglia (UK)", "University of Stirling (UK)", "Trinity College Dublin (Ireland)",
        "University College Dublin (Ireland)", "University of Galway (Ireland)", "University of Edinburgh (Scotland)",
        "University of Aberdeen (Scotland)", "University of Glasgow (Scotland)", "University of St Andrews (Scotland)",
        "Aston University (UK)", "University of Newcastle (UK)", "University of Bath (UK)", "University of Liverpool (UK)",
        "University of Oxford Brookes (UK)", "University of Greenwich (UK)", "Queen Mary University of London (UK)",
        "University of Manchester Institute of Science and Technology (UMIST) (UK)", "University of East London (UK)",
        "University of West London (UK)", "University of Portsmouth (UK)", "University of Huddersfield (UK)",
        "University of South Wales (UK)", "University of Plymouth (UK)", "University of Lincoln (UK)", "University of Derby (UK)",
        "University of Staffordshire (UK)", "University of Leicester (UK)", "University of Hertfordshire (UK)", "University of London (UK)",
        "Loughborough University (UK)", "University of Chester (UK)", "University of Surrey (UK)", "University of Brighton (UK)",
        "Oxford Brookes University (UK)", "Kingston University (UK)", "University of Westminster (UK)",
        "University of Central Lancashire (UK)", "London Metropolitan University (UK)", "Anglia Ruskin University (UK)",
        "London South Bank University (UK)", "University of Hertfordshire (UK)", "University of Bedfordshire (UK)",
        "De Montfort University (UK)", "University of Northampton (UK)", "University of Warwick (UK)", "University of Manchester (UK)",
        "University of Bristol (UK)", "University of Oxford (UK)", "University of Cambridge (UK)", "University of Kent (UK)",
        "University of Sunderland (UK)", "University of Nottingham (UK)", "University of Edinburgh (UK)",
        "Northumbria University (UK)", "The University of Stirling (UK)", "University of the West of England (UK)",
        "Manchester Metropolitan University (UK)", "Coventry University (UK)", "University of Dundee (UK)",
        "University of Swansea (UK)", "London School of Economics (UK)", "University of South Wales (UK)", "University of Wales (UK)",
        "University of Derby (UK)", "University of South Wales (UK)", "University of Stirling (UK)", "University of Leeds (UK)",
        "University of East Anglia (UK)", "University of Bath (UK)", "University of Kent (UK)", "University of Stirling (UK)",
        "University of Zurich (Switzerland)", "ETH Zurich (Switzerland)", "University of Lausanne (Switzerland)",
        "University of Geneva (Switzerland)", "University of Bern (Switzerland)", "University of Fribourg (Switzerland)",
        "University of Basel (Switzerland)", "University of Lucerne (Switzerland)", "Bocconi University",
        "University of Pisa (Italy)", "University of Florence (Italy)", "Politecnico di Torino (Italy)",
        "Polytechnic University of Milan", "University of Naples Federico II (Italy)", "University of Catania (Italy)",
        "University of Rome La Sapienza (Italy)", "University of Bologna (Italy)", "University of Padua (Italy)",
        "Catholic University of the Sacred Heart",
        "University of Perugia (Italy)", "University of Trento (Italy)", "University of Milan",
        "University of Cagliari (Italy)", "Lund University (Sweden)", "Karolinska Institute (Sweden)",
        "Chalmers University of Technology (Sweden)", "Stockholm School of Economics (Sweden)", "Uppsala University (Sweden)",
        "Aarhus University (Denmark)", "University of Copenhagen (Denmark)", "Technical University of Denmark (Denmark)",
        "University of Helsinki (Finland)", "University of Turku (Finland)", "University of Lapland (Finland)",
        "University of Iceland (Iceland)", "University of Oslo (Norway)", "Norwegian University of Science and Technology (NTNU)",
        "University of Bergen (Norway)", "University of Stavanger (Norway)", "University of Porto (Portugal)",
        "University of Lisbon (Portugal)", "Nova University of Lisbon (Portugal)", "University of Coimbra (Portugal)",
        "University of Belgrade (Serbia)", "University of Zagreb (Croatia)", "University of Ljubljana (Slovenia)",
        "University of Sofia (Bulgaria)", "University of Bucharest (Romania)", "University of Warsaw (Poland)",
        "Jagiellonian University (Poland)", "Adam Mickiewicz University in Poznań (Poland)", "University of Wrocław (Poland)",
        "University of Moscow (Russia)", "Saint Petersburg State University (Russia)", "Moscow Institute of Physics and Technology (Russia)",
        "University of St. Petersburg (Russia)", "Lomonosov Moscow State University (Russia)", "University of Belgrade (Serbia)",
        "Tbilisi State University (Georgia)", "Baku State University (Azerbaijan)", "University of Vilnius (Lithuania)"
    )

}